version: '3.3'
volumes:
  task_manager_db_volume:
services:
  task_manager:
    env_file:
      - .env
    container_name: ${PREFIX}
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PREFIX}
    ports:
      - "5000:5000"
    volumes:
      - .:/app