version: '3.8'
volumes:
  task_manager_db_volume:
services:
  database:
    container_name: ${PREFIX}
    image: sqlite3
    restart: always
    volumes:
      - task_manager_db_volume:/var/lib/sqlite3/data
  task_manager:
    container_name: ${PREFIX}
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PREFIX}
    restart: always
    depends_on:
      - database